[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic_staking = "HUjbRStzkMdzaYjJ22kfQfXJG6V4RqPLUfD9e4qe4j54"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
